import test from 'node:test';
import assert from 'node:assert/strict';
import {validateGraph,compileTSL,createStarterGraph,getSupportedOperations} from '../src/core/graph.mjs';
import {validateScene,createEditorStore,blankObject} from '../src/core/scene-state.mjs';
import {PRESETS,resolvePreset,chooseFxQuality} from '../src/core/postfx.mjs';
import {createTimeline,nearestFrame} from '../src/core/timeline.mjs';
import {validateSplatAsset,recommendSplatSettings} from '../src/core/splat.mjs';
import {createRendererRegistry,assertNoDuplicateSources} from '../src/core/interop.mjs';

test('shader graph starter compiles TSL',()=>{const g=createStarterGraph();assert.equal(validateGraph(g).ok,true);assert.match(compileTSL(g),/export const colorNode/);});
test('graph rejects duplicate node ID',()=>{const g=createStarterGraph();g.nodes.push({...g.nodes[0]});assert.equal(validateGraph(g).ok,false);});
test('graph rejects forbidden ops',()=>{const g=createStarterGraph();g.nodes[0].op='eval';assert.equal(validateGraph(g).ok,false);});
test('graph rejects unknown dependencies',()=>{const g=createStarterGraph();g.nodes.at(-1).inputs.color='bad';assert.equal(validateGraph(g).ok,false);});
test('graph cycle is found',()=>{let g={nodes:[{id:'a',op:'sin',inputs:{input:'b'}},{id:'b',op:'sin',inputs:{input:'a'}},{id:'out',op:'output',inputs:{color:'a'}}]};assert.equal(validateGraph(g).ok,false);});
test('graph numeric formatting preserves integer hundreds',()=>{const g=createStarterGraph();g.nodes[0].value=[100,10,1];assert.match(compileTSL(g),/vec3\(100, 10, 1\)/);});
test('graph rejects symbol alias collisions',()=>{const g=createStarterGraph();g.nodes.splice(1,0,{id:'a-b',op:'float',value:1},{id:'a_b',op:'float',value:2});assert.equal(validateGraph(g).ok,false);});
test('graph unsafe symbol names rejected',()=>{const g=createStarterGraph();g.nodes[0].id='alert()';assert.equal(validateGraph(g).ok,false);});
test('graph supports documented node operators',()=>assert.ok(getSupportedOperations().includes('mix')));
test('scene document validates and rejects duplicate',()=>{const o=blankObject('box');assert.equal(validateScene({version:1,objects:[o]}).ok,true);assert.equal(validateScene({version:1,objects:[o,o]}).ok,false);});
test('scene rejects NaN transform',()=>{const o=blankObject('x');o.position[0]=NaN;assert.equal(validateScene({version:1,objects:[o]}).ok,false);});
test('scene store undo/redo',()=>{const s=createEditorStore();s.transact(d=>d.objects.push(blankObject('cube')));assert.equal(s.read().objects.length,1);assert.equal(s.undo(),true);assert.equal(s.read().objects.length,0);assert.equal(s.redo(),true);assert.equal(s.read().objects.length,1);});
test('scene rollback on invalid candidate',()=>{const s=createEditorStore();assert.throws(()=>s.transact(d=>d.objects.push({...blankObject('x'),scale:[0,0,0]})));assert.equal(s.read().objects.length,0);});
test('scene import JSON protects state',()=>{const s=createEditorStore();assert.throws(()=>s.importJSON('{"version":1,"objects":[{"id":"evil"}]}'));assert.equal(s.read().objects.length,0);});
test('postfx preset normalizes mobile load',()=>{const p=resolvePreset('neon','mobile');assert.ok(p.bloomIntensity<=.3);assert.equal(p.grain,0);});
test('postfx rejects invalid',()=>assert.throws(()=>resolvePreset('missing')));
test('postfx quality chooses low on high load',()=>assert.equal(chooseFxQuality({width:1080,height:2400,dpr:3,frameP95:44}),'low'));
test('postfx presets do not mutate originals',()=>{const old=PRESETS.neon.bloomIntensity;resolvePreset('neon','low');assert.equal(PRESETS.neon.bloomIntensity,old);});
test('clock supports pause, seek, reverse',()=>{const t=createTimeline({duration:10});t.seek(7);t.rate(-1);t.play();t.tick(0);t.tick(1000);assert.equal(t.read().time,6.75);t.pause();assert.equal(t.read().playing,false);});
test('clock bounds non-loop',()=>{const t=createTimeline({duration:5});assert.equal(t.seek(99),5);assert.equal(t.seek(-20),0);});
test('clock can loop',()=>{const t=createTimeline({duration:5,loop:true});assert.equal(t.seek(6),1);});
test('clock input validation',()=>assert.throws(()=>createTimeline({duration:0})));
test('frame numbers deterministic',()=>assert.equal(nearestFrame(2,30),60));
test('splat accepts local .splat',()=>assert.equal(validateSplatAsset({url:'/assets/a.splat',bytes:1000}).ok,true));
test('splat rejects protocol relative origins',()=>assert.equal(validateSplatAsset({url:'//evil.example/my.splat'}).ok,false));
test('splat rejects remote and oversized file',()=>{assert.equal(validateSplatAsset({url:'https://bad/a.splat'}).ok,false);assert.equal(validateSplatAsset({url:'/assets/a.splat',bytes:3e8}).ok,false);});
test('splat mobile policy limits dpr',()=>assert.ok(recommendSplatSettings({memoryGB:2}).dprCap<=1.25));
test('renderer owner registry refuses duplicate',()=>{const c={};const reg=createRendererRegistry();const release=reg.acquire(c,'a');assert.throws(()=>reg.acquire(c,'b'));release();assert.equal(reg.owner(c),null);});
test('transform owner conflict rejected',()=>assert.throws(()=>assertNoDuplicateSources([{name:'gsap',ownedProperties:['hero.rotation']},{name:'three',ownedProperties:['hero.rotation']}])));
