import {transitionView,configureNativeShared, parallaxTransform,revealMask,typographyPlan,gridMotion,applyMotion,normalizeShapes,morphPoints,pointsToPath,frameForProgress,materialOptions,Spring,spatialNavPath,ProductConfigurator,ReadinessGate,editorialGrid,prefersReducedMotion} from '../../src/index.mjs';
const $=q=>document.querySelector(q);const reduce=()=>prefersReducedMotion();let stage='a';
$('#transition-btn').addEventListener('click',async()=>{
 const host=$('.transition-display');configureNativeShared();const next=stage==='a'?'b':'a';const result=await transitionView({root:host,duration:450,reducedMotion:reduce(),update:async()=>{stage=next;host.dataset.stage=next;$('#shared-title').textContent=next==='b'?'B / NEW FORM':'A / FIRST FORM';$('#shared-kicker').textContent=next==='b'?'ANIMATED TRANSFORMATION':'SPATIAL CONTINUITY';}});host.dataset.lastEngine=result.engine??result.status;
});
const artwork=$('#parallax-image');let revealing=false;$('#image-btn').addEventListener('click',()=>{revealing=!revealing;$('#image-mask').style.clipPath=revealMask(revealing?1:0);$('#image-btn').textContent=revealing?'HIDE ↗':'REVEAL ↗'});$('.image-display').addEventListener('pointermove',e=>{if(reduce())return;const box=e.currentTarget.getBoundingClientRect(),o=parallaxTransform({pointerX:((e.clientX-box.left)/box.width-.5)*2,pointerY:((e.clientY-box.top)/box.height-.5)*2,depth:1,intensity:15});artwork.style.transform=`translate(${o.x}px,${o.y}px) scale(1.1)`});$('.image-display').addEventListener('pointerleave',()=>{artwork.style.transform='scale(1.09)'});
let persian=false;$('#type-btn').addEventListener('click',()=>{persian=!persian;const text=persian?'فرم تازه':'NEW\nFORM.';const plan=typographyPlan(text,persian?'fa':'en');$('#kinetic-title').textContent=text;$('#kinetic-title').setAttribute('lang',plan.locale);$('#kinetic-title').setAttribute('dir',plan.dir);$('#kinetic-title').style.setProperty('--type-y',reduce()?'0px':'-10px');$('#kinetic-title').style.setProperty('--type-stretch',reduce()?'1':'1.045');setTimeout(()=>{$('#kinetic-title').style.setProperty('--type-y','0px');$('#kinetic-title').style.setProperty('--type-stretch','1')},180)});
const tiles=[...$('#layout-display').querySelectorAll('.tile')];$('#layout-slider').addEventListener('input',e=>{const states=gridMotion(tiles.map((el,i)=>({id:String(i),depth:(i+1)/4})),e.target.value/100);states.forEach((state,i)=>applyMotion(tiles[i],reduce()?{}:state))});
const [shapeA,shapeB]=normalizeShapes([[130,40],[220,40],[220,140],[130,140]],[[170,16],[270,120],[190,225],[70,195],[62,78]],80);function morph(t){$('#morph-path').setAttribute('d',pointsToPath(morphPoints(shapeA,shapeB,t)))}morph(0);$('#morph-slider').addEventListener('input',e=>morph(e.target.value/100));
$('#story-slider').addEventListener('input',e=>{const i=frameForProgress(e.target.value/100,48);$('#story-frame').src=`./assets/frames/${String(i).padStart(3,'0')}.svg`;$('#story-index').textContent=`${String(i+1).padStart(3,'0')} / 048`});
$('#material-select').addEventListener('change',e=>{materialOptions(e.target.value);$('#material-sphere').className='material-sphere '+e.target.value});
const spring=new Spring({position:0,target:0,mass:1,stiffness:100,damping:17});let last=0;function physicsTick(ts){const dt=Math.min(.04,Math.max(0,(ts-last)/1000||0));last=ts;if(reduce()){spring.position=spring.target;spring.velocity=0}else spring.step(dt);$('#spring-ball').style.setProperty('--spring-x',spring.position.toFixed(2)+'px');requestAnimationFrame(physicsTick)}requestAnimationFrame(physicsTick);$('#physics-display').addEventListener('pointermove',e=>{const b=e.currentTarget.getBoundingClientRect();spring.target=Math.max(-Math.min(110,b.width*.22),Math.min(Math.min(110,b.width*.22),e.clientX-b.left-b.width/2))});$('#physics-btn').addEventListener('click',()=>spring.target=0);
let currentNode=0;const nodes=[{id:'0',x:0,y:0},{id:'1',x:1,y:0},{id:'2',x:2,y:0}];function navTo(i){currentNode=(i+3)%3;$('.nav-display').style.setProperty('--nav-angle',`${(i-1)*12}deg`);$('#nav-label').textContent=`SCENE / ${['ONE','TWO','THREE'][currentNode]}`;document.querySelectorAll('[data-node]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.node)===currentNode);b.setAttribute('aria-pressed',String(Number(b.dataset.node)===currentNode))})}document.querySelectorAll('[data-node]').forEach(b=>b.addEventListener('click',()=>navTo(Number(b.dataset.node))));$('#nav-next').addEventListener('click',()=>navTo(currentNode+1));$('.nav-display').addEventListener('keydown',e=>{if(e.key!=='ArrowRight'&&e.key!=='ArrowLeft')return;const id=spatialNavPath(nodes,String(currentNode),e.key==='ArrowRight'?'right':'left');if(id!=null){navTo(Number(id));document.querySelector(`[data-node="${id}"]`)?.focus()}e.preventDefault()});navTo(0);
const config=new ProductConfigurator({color:{options:['red','blue'],default:'red'},trim:{options:['silver','black'],default:'silver'}});function renderConfig(){const snap=config.snapshot();$('#product-preview').style.setProperty('--product-color',snap.color==='red'?'#e65b4e':'#4066a9');$('#product-preview').querySelector('.product-lens').style.boxShadow=snap.trim==='silver'?'inset 0 0 0 2px #eee':'inset 0 0 0 2px #0f1219';$('#config-summary').textContent=`${snap.color.toUpperCase()} / ${snap.trim.toUpperCase()}`}$('#config-color').addEventListener('click',()=>{config.update('color',config.state.color==='red'?'blue':'red');renderConfig()});$('#config-wheel').addEventListener('click',()=>{config.update('trim',config.state.trim==='silver'?'black':'silver');renderConfig()});renderConfig();
$('#intro-btn').addEventListener('click',async()=>{const status=$('#intro-status'),progress=$('#intro-progress');status.textContent='VERIFYING REAL TASKS';progress.style.width='0';const gate=new ReadinessGate([{name:'fonts',run:()=>document.fonts.ready},{name:'hero-art',run:()=>artwork.decode()},{name:'svg',run:async()=>{if(!$('#morph-path').getAttribute('d'))throw Error('SVG missing')}}]);const result=await gate.start({onProgress:(p)=>{progress.style.width=`${Math.round(p*100)}%`}});status.textContent=result.status==='ready'?'ALL ASSETS READY':'ASSET CHECK FAILED';});
$('#editorial-btn').addEventListener('click',()=>{const grid=editorialGrid([{kind:'headline',id:'a'},{kind:'image',id:'b',alt:'product'}],{seed:Math.floor(Math.random()*1000),viewport:window.innerWidth});$('.editorial-mast').style.flexDirection=grid.placements[1].col%2?'row-reverse':'row'});
