/** Perfect_AI Shader Graph v1: safe, deterministic graph compiler. No eval or user code execution. */
const OPS = new Set(['float','vec3','uv','time','add','subtract','multiply','divide','sin','cos','mix','clamp','output']);
const NAMES = /^[A-Za-z][\w-]{0,63}$/;
export function validateGraph(input) {
  const errors=[];
  if (!input || typeof input !== 'object' || !Array.isArray(input.nodes)) return {ok:false,errors:['nodes must be an array']};
  if (input.nodes.length>256) errors.push('maximum 256 nodes');
  const nodes=new Map(),aliases=new Set();
  for(const n of input.nodes){
    if(!n||typeof n!=='object'||!NAMES.test(n.id??'')){errors.push('invalid node id');continue;}
    if(nodes.has(n.id)) errors.push('duplicate node '+n.id); const alias=n.id.replaceAll('-','_'); if(aliases.has(alias))errors.push('ambiguous normalized node name '+n.id);aliases.add(alias);
    if(!OPS.has(n.op)) errors.push('unsupported node op: '+n.op);
    nodes.set(n.id,n);
  }
  const deps=(n)=> Object.values(n.inputs??{}).filter(x=>typeof x==='string');
  for(const n of nodes.values()){
    for(const d of deps(n)) if(!nodes.has(d))errors.push(`${n.id}: missing input ${d}`);
    if(n.op==='float' && (!Number.isFinite(n.value)||Math.abs(n.value)>1e6))errors.push(`${n.id}: invalid float`);
    if(n.op==='vec3' && (!Array.isArray(n.value)||n.value.length!==3||n.value.some(x=>!Number.isFinite(x)||Math.abs(x)>1e6))) errors.push(`${n.id}: invalid vec3`);
  }
  const visited=new Set(), visiting=new Set(),order=[];
  function dfs(id){if(visiting.has(id)){errors.push('cycle at '+id);return;}if(visited.has(id))return;visiting.add(id);for(const d of deps(nodes.get(id)))if(nodes.has(d))dfs(d);visiting.delete(id);visited.add(id);order.push(id);}
  for(const id of nodes.keys())dfs(id);
  const outputs=[...nodes.values()].filter(x=>x.op==='output');
  if(outputs.length!==1) errors.push('expected exactly one output node');
  if(input.nodes.length===0) errors.push('empty graph');
  return {ok:errors.length===0,errors,order,nodes};
}
const fin=(x)=>String(Number(Number(x).toFixed(6)));
export function compileTSL(graph){
 const v=validateGraph(graph);if(!v.ok) throw new Error(v.errors.join('; '));
 const lookup=new Map();const lines=[];
 const need=(n,key,defaultValue=null)=>{const id=n.inputs?.[key];if(!id)return defaultValue;if(!lookup.has(id))throw new Error(`invalid edge ${n.id}/${key}`);return lookup.get(id);};
 const varName=id=>'n_'+id.replaceAll('-','_');
 for(const id of v.order){const n=v.nodes.get(id), name=varName(id);let expr;
  switch(n.op){
   case 'float':expr=`float(${fin(n.value)})`;break;
   case 'vec3':expr=`vec3(${n.value.map(fin).join(', ')})`;break;
   case 'uv':expr='uv()';break;
   case 'time':expr='time';break;
   case 'add':case 'subtract':case 'multiply':case 'divide':{
      const a=need(n,'a'), b=need(n,'b');if(!a||!b)throw new Error(`${id}: missing operands`);
      expr=`${a}.${({add:'add',subtract:'sub',multiply:'mul',divide:'div'})[n.op]}(${b})`;break;
   }
   case 'sin':case 'cos':{const a=need(n,'input');if(!a)throw new Error(`${id}: missing input`);expr=`${a}.${n.op}()`;break;}
   case 'clamp':{const a=need(n,'input'),lo=need(n,'min'),hi=need(n,'max');if(!a||!lo||!hi)throw new Error(`${id}: missing clamp input`);expr=`${a}.clamp(${lo}, ${hi})`;break;}
   case 'mix':{const a=need(n,'a'),b=need(n,'b'),t=need(n,'t');if(!a||!b||!t)throw new Error(`${id}: missing mix input`);expr=`${a}.mix(${b}, ${t})`;break;}
   case 'output':{const x=need(n,'color');if(!x)throw new Error('output missing color');expr=x;break;}
  }
  if(n.op==='output')lines.push(`export const colorNode = ${expr};`);
  else {lines.push(`const ${name} = ${expr};`);lookup.set(id,name);}
 }
 return `// Generated by Perfect_AI, review output before executing.\nimport { float, vec3, uv, time } from 'three/tsl';\n${lines.join('\n')}\n`;
}
export function createStarterGraph(){return {version:1,nodes:[{id:'base',op:'vec3',value:[0.13,0.45,0.95],x:35,y:40},{id:'out',op:'output',inputs:{color:'base'},x:325,y:90}]};}
export function getSupportedOperations(){return [...OPS];}
